export {
  UserOutline,
  LockOutline,
  MailOutline,
  PhoneOutline,
  QqOutline,
  CopyOutline,
  LoadingOutline,
  CheckOutline,
  CheckCircleFill,
  PlusOutline,
  EditOutline,
  StarOutline,
  PlusCircleOutline,
  MinusCircleOutline,
  StarFill,
  UpOutline,
  DownOutline,
  CloseCircleFill,
  InfoOutline
} from '@ant-design/icons'
